"""Upgrade Report Table

Revision ID: 1d2d3df92e5d
Revises: c1f6a3d0cc4f
Create Date: 2025-03-07 15:26:10.407592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d2d3df92e5d'
down_revision: Union[str, None] = 'c1f6a3d0cc4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('report', sa.Column('topic_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'report', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'report', 'topic', ['topic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_column('report', 'topic_id')
    op.drop_column('report', 'user_id')
    # ### end Alembic commands ###
