"""new tables

Revision ID: 31c705cbeba6
Revises: 861f80a8037a
Create Date: 2025-03-12 15:54:17.411374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31c705cbeba6'
down_revision: Union[str, None] = '861f80a8037a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('customer_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'customer_id')
    # ### end Alembic commands ###
