"""Upgrade existing Table

Revision ID: 354025c743a0
Revises: 73bb1b3e2c14
Create Date: 2025-03-07 10:30:36.917889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '354025c743a0'
down_revision: Union[str, None] = '73bb1b3e2c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('report_user_id_fkey', 'report', type_='foreignkey')
    op.drop_constraint('report_topic_id_fkey', 'report', type_='foreignkey')
    op.drop_column('report', 'user_id')
    op.drop_column('report', 'topic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('topic_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('report', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('report_topic_id_fkey', 'report', 'topic', ['topic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('report_user_id_fkey', 'report', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
