"""Upgrade existing Table

Revision ID: 42f021589375
Revises: 5fbc0a7ab3a1
Create Date: 2025-03-07 11:33:28.193855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f021589375'
down_revision: Union[str, None] = '5fbc0a7ab3a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_session', sa.Column('reprt_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'conversation_session', 'report', ['reprt_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation_session', type_='foreignkey')
    op.drop_column('conversation_session', 'reprt_id')
    # ### end Alembic commands ###
