"""Upgrade existing Table

Revision ID: 524c2927fa63
Revises: 9e2ddcaf9f9f
Create Date: 2025-03-05 18:02:53.049409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524c2927fa63'
down_revision: Union[str, None] = '9e2ddcaf9f9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
