"""updated tables

Revision ID: 58640a838c60
Revises: ed23fb998a3a
Create Date: 2025-03-04 15:12:03.348805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58640a838c60'
down_revision: Union[str, None] = 'ed23fb998a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['id'])
    op.create_unique_constraint(None, 'conversation', ['id'])
    op.create_unique_constraint(None, 'conversation_session', ['id'])
    op.create_unique_constraint(None, 'report', ['id'])
    op.create_unique_constraint(None, 'topic', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic', type_='unique')
    op.drop_constraint(None, 'report', type_='unique')
    op.drop_constraint(None, 'conversation_session', type_='unique')
    op.drop_constraint(None, 'conversation', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
