"""Upgrade existing Table

Revision ID: 5fbc0a7ab3a1
Revises: 36f5db2e11bd
Create Date: 2025-03-07 11:21:16.303292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fbc0a7ab3a1'
down_revision: Union[str, None] = '36f5db2e11bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversation_session_report_id_fkey', 'conversation_session', type_='foreignkey')
    op.drop_column('conversation_session', 'report_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_session', sa.Column('report_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('conversation_session_report_id_fkey', 'conversation_session', 'report', ['report_id'], ['id'])
    # ### end Alembic commands ###
