"""new columns

Revision ID: 63e7281f39ee
Revises: f1703795284d
Create Date: 2025-03-18 10:57:16.064992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63e7281f39ee'
down_revision: Union[str, None] = 'f1703795284d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('allowed_conversations', sa.Integer() , nullable=True))
    op.add_column('user', sa.Column('used_conversations', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'used_conversations')
    op.drop_column('plan', 'allowed_conversations')
    # ### end Alembic commands ###
