"""Upgrade Report Table

Revision ID: 73bb1b3e2c14
Revises: 528bc8f3e11b
Create Date: 2025-03-06 17:51:46.625030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73bb1b3e2c14'
down_revision: Union[str, None] = '528bc8f3e11b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('report', sa.Column('topic_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'report', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'report', 'topic', ['topic_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_column('report', 'topic_id')
    op.drop_column('report', 'user_id')
    # ### end Alembic commands ###
