"""new tables

Revision ID: 8e107ff51396
Revises: f9ee95eb072a
Create Date: 2025-03-13 15:44:00.743132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e107ff51396'
down_revision: Union[str, None] = 'f9ee95eb072a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'plan', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plan', type_='unique')
    # ### end Alembic commands ###
