"""Change Subscription table

Revision ID: 960358bb93dc
Revises: 94cc94497b41
Create Date: 2025-03-22 11:58:42.572766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '960358bb93dc'
down_revision: Union[str, None] = '94cc94497b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['id'])
    op.create_unique_constraint(None, 'conversation', ['id'])
    op.create_unique_constraint(None, 'conversation_session', ['id'])
    op.create_unique_constraint(None, 'invoice', ['id'])
    op.create_unique_constraint(None, 'payment', ['id'])
    op.create_unique_constraint(None, 'plan', ['id'])
    op.create_unique_constraint(None, 'report', ['id'])
    op.create_unique_constraint(None, 'subscription', ['id'])
    op.create_unique_constraint(None, 'topic', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'topic', type_='unique')
    op.drop_constraint(None, 'subscription', type_='unique')
    op.drop_constraint(None, 'report', type_='unique')
    op.drop_constraint(None, 'plan', type_='unique')
    op.drop_constraint(None, 'payment', type_='unique')
    op.drop_constraint(None, 'invoice', type_='unique')
    op.drop_constraint(None, 'conversation_session', type_='unique')
    op.drop_constraint(None, 'conversation', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
