"""Upgrade existing Table

Revision ID: 9e2ddcaf9f9f
Revises: cb98656eb9da
Create Date: 2025-03-05 18:02:43.130399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2ddcaf9f9f'
down_revision: Union[str, None] = 'cb98656eb9da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(), nullable=True))
    op.drop_index('ix_user_firstname', table_name='user')
    op.drop_index('ix_user_lastname', table_name='user')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_user_lastname', 'user', ['lastname'], unique=False)
    op.create_index('ix_user_firstname', 'user', ['firstname'], unique=False)
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
