"""Upgrade existing Table

Revision ID: a8718c65fe86
Revises: 42f021589375
Create Date: 2025-03-07 11:58:32.792606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8718c65fe86'
down_revision: Union[str, None] = '42f021589375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversation_session_reprt_id_fkey', 'conversation_session', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_session', 'report', ['reprt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation_session', type_='foreignkey')
    op.create_foreign_key('conversation_session_reprt_id_fkey', 'conversation_session', 'report', ['reprt_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
