"""Upgrade existing Table

Revision ID: b2222150296a
Revises: 354025c743a0
Create Date: 2025-03-07 10:35:21.790010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2222150296a'
down_revision: Union[str, None] = '354025c743a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_session', sa.Column('report_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'conversation_session', 'report', ['report_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation_session', type_='foreignkey')
    op.drop_column('conversation_session', 'report_id')
    # ### end Alembic commands ###
