"""Upgrade existing Table

Revision ID: c1f6a3d0cc4f
Revises: 07fd175e8d4a
Create Date: 2025-03-07 12:02:10.098451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1f6a3d0cc4f'
down_revision: Union[str, None] = '07fd175e8d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversation_session_reprt_id_fkey', 'conversation_session', type_='foreignkey')
    op.drop_column('conversation_session', 'reprt_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_session', sa.Column('reprt_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('conversation_session_reprt_id_fkey', 'conversation_session', 'report', ['reprt_id'], ['id'])
    # ### end Alembic commands ###
