"""new tables

Revision ID: f9ee95eb072a
Revises: ca67c360bf28
Create Date: 2025-03-13 11:38:16.778171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ee95eb072a'
down_revision: Union[str, None] = 'ca67c360bf28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('price_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('interval', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('price_id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_unique_constraint(None, 'invoice', ['id'])
    op.create_unique_constraint(None, 'payment', ['id'])
    op.add_column('subscription', sa.Column('plan_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'subscription', ['id'])
    op.create_foreign_key(None, 'subscription', 'plan', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_constraint(None, 'subscription', type_='unique')
    op.drop_column('subscription', 'plan_id')
    op.drop_constraint(None, 'payment', type_='unique')
    op.drop_constraint(None, 'invoice', type_='unique')
    op.drop_table('plan')
    # ### end Alembic commands ###
