"""Upgrade existing table

Revision ID: e146008e9095
Revises: 8f96f75b1ca0
Create Date: 2025-02-07 11:22:30.884918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e146008e9095'
down_revision = '8f96f75b1ca0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
