"""Upgrade existing table

Revision ID: 8f96f75b1ca0
Revises: 0d716b5aa63b
Create Date: 2025-02-07 11:19:54.123570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f96f75b1ca0'
down_revision = '0d716b5aa63b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(), nullable=True))
    op.drop_index('ix_user_firstname', table_name='user')
    op.drop_index('ix_user_lastname', table_name='user')
    op.drop_constraint('user_phone_number_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_unique_constraint(None, 'user', ['id'])
    op.drop_column('user', 'firstname')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'phone_number_verified')
    op.drop_column('user', 'image_url')
    op.drop_column('user', 'phone_number_country_code')
    op.drop_column('user', 'lastname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('phone_number_country_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('phone_number_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_unique_constraint('user_phone_number_key', 'user', ['phone_number'])
    op.create_index('ix_user_lastname', 'user', ['lastname'], unique=False)
    op.create_index('ix_user_firstname', 'user', ['firstname'], unique=False)
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
